// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKNnSMprpMuPnbWmr1SmVI6jBvkuig4OY',
    appId: '1:328618475164:web:aa1be385065bf0f6daf759',
    messagingSenderId: '328618475164',
    projectId: 'flutter-uib',
    authDomain: 'flutter-uib.firebaseapp.com',
    storageBucket: 'flutter-uib.appspot.com',
    measurementId: 'G-E2K3GSY8CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUTKPwpngZ0R4aM0ov3l9R-eWRVx-kWVM',
    appId: '1:328618475164:android:b3e9046e6ed64164daf759',
    messagingSenderId: '328618475164',
    projectId: 'flutter-uib',
    storageBucket: 'flutter-uib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBQcTYKGCyN1r6NlvgPVN7ZjqJN2F4KA',
    appId: '1:328618475164:ios:d55357f3a06e5e80daf759',
    messagingSenderId: '328618475164',
    projectId: 'flutter-uib',
    storageBucket: 'flutter-uib.appspot.com',
    iosBundleId: 'com.example.flutterAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBQcTYKGCyN1r6NlvgPVN7ZjqJN2F4KA',
    appId: '1:328618475164:ios:3c0ed533ee045329daf759',
    messagingSenderId: '328618475164',
    projectId: 'flutter-uib',
    storageBucket: 'flutter-uib.appspot.com',
    iosBundleId: 'com.example.flutterAppNew.RunnerTests',
  );
}

final fcmToken = FirebaseMessaging.instance.getToken();